### ISSUE TITLE
How to access administration dashboard

### ISSUE THREAD

**Issue by sargon** [DigitalCurationCentre/DMPonline_v4#104]
Hi,

I have followed the local installation guide from the wiki pages. On the running instance I am able to create new user accounts via the registration formula. But I am unable to create
own organisations, so when I click on "Create Plan" in my User View. All I get is a "undefined method `organisations' for nil:NilClass" error. From my understanding of the code there should be a admin dashboard, but I am unable to access it. Can you please extend the documentation about this part of the application.

regards Daniel

**Comment by chrisblack910** [comment]
Hi all.
I am having the same problem of not being able to access the admin dashboard. Did anyone manage to solve this?

Thanks.

**Comment by sjDCC** [comment]
I don't know if this helps, but here's a (non-techie) response I've given to a similar query to dmponline@dcc.ac.uk

You need to grant yourself org_admin rights under the super admin area first, then the admin option will appear for you in the dropdown. To do this, open your profile in the super admin interface by clicking 'edit user'. Check that you have the correct organisational affiliation (i.e. a named organisation in the database, not 'other org'), and then click the ‘org_admin’ option to assign rights.

Two screengrabs are attached to help you find these options

All best

Sarah
![edit-profile](https://cloud.githubusercontent.com/assets/6169940/12614587/cb2e1c7c-c4f8-11e5-9e26-9309d9c3896a.png)
![granting-org-admin-rights](https://cloud.githubusercontent.com/assets/6169940/12614588/cb31174c-c4f8-11e5-92d1-0f61a7551443.png)

**Comment by chrisblack910** [comment]
I know I am now going off topic but after I create a plan I am unable to see any of the questions one is suppose to answer. Kindly help. I have not been getting any response from the DCC people with regards to this. This is all I get. Only able to see the questions if I manually change things in the database i.e. linking plan to project.

![errorhelp](https://cloud.githubusercontent.com/assets/16719699/12615070/382d68e2-c50c-11e5-8f65-4487e8551be4.JPG)

**Comment by gonter** [comment]
Are you aware of the dmponline list?  Maybe your question can be answered there, at least there are active participants from dcc.ac.uk posting messages and answers.

To answer the question about the admin rights: I had to change that in MySQL myself by adding my user as admin user:

check if you have "admin" and "org_admin" in roles:

  select * from roles;

if not, add them, e.g.:
insert into roles (name) values('admin');
insert into roles (name) values('org_admin');

Then find out your user_id:
select id from users where email='my-email@address';

and make yourself an admin:
insert into users_roles values(2, 1);
(my user_id was 2, the role 'admin' has 1 in our database)

* [1] https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=dmponline-user-group

HTH, GG

**Comment by sjDCC** [comment]
Hi Chris,

Sorry we didn't get to your earlier query, but it looks like you've fixed that in the interim.

When you download DMPonline from GitHub you just get the code, not the content. Essentially it's an empty shell so people can add templates and guidance related to their own context. Looking at the screengrab it seems you've added AHRC as a funder and University of Glasgow as a uni, but if there aren't any templates or guidance associated with these organisations in your database, then the tool won't have any content to present.

The DCC has a generic template online (http://www.dcc.ac.uk/sites/default/files/documents/resource/DMP/DMP_Checklist_2013.pdf) and details about UK funder policies so you could abstract details from these http://www.dcc.ac.uk/resources/data-management-plans/funders-requirements. If you're based in the UK though, it may just be easiest to use the DCC-hosted instance which includes all the relevant templates, see: https://dmponline.dcc.ac.uk to save you running your own instance

All best

Sarah

**Comment by chrisblack910** [comment]
Hi Sarah,

After I create a plan on the tool, it gets saved in the project table which is fine. However, In my understanding, it should link this project with a plans and plan_sections (which contain the section answers) meaning after it creates the plan in project table, it should also create links in the plans table and in the plan_sections table (hope I am making sense). In my case, it just creates the plan in project table and the plan and plan_section tables are blank - hence the screenshot I attached earlier of what my view currently looks like. When I do manually add links in the plans and plan_sections table, the tool shows the questions. However I cannot do this for every user if this tool is used in the organisation. If I effect these changes manually, than the tool for me is not performing as I would expect it as this defeats the purpose of the tool.

I have added templates and guidances to link the funders/institutions I have in my database as you suggested however the problem persists.

**Comment by martaribeiro** [comment]
Hi Gerhard and Chris,

I have to apologise for the delayed reply, but I have been busy with DMPonline live instance... Sorry. Thank you Gerhard for answering Chris, and thank you Sarah. 

The latest seed file has 'roles' loaded with data. However, I still haven't manage to load the seeds file with an user. There is a problem in the code between line 81 to 115 of the seeds file. If it's commented out, then you can run 'rake db:setup' and a database with some data will be created. But after, you will need to create an user and then in the mysql, you will need to link the user to 'roles' as Gerhard said. Once this is done you will have full access to the back end of the tool.


Once again sorry for the delay,
Marta

**Comment by chrisblack910** [comment]
Hi Gonter

thanks will take a look at the list. Appreciated.

Regards,
Chris

**Comment by martaribeiro** [comment]
Hi Chris,

I'm not sure why you are getting that problem, it looks like you are missing models, specifically plan.rb and plan_section.rb. Those files are responsible for the connection between tables so it seems like you've got something missing there. 

When did you download the code from github?  Do you have any problems when compiling? 

If you're not familiar with using Ruby, this website might help: http://betterexplained.com/articles/intermediate-rails-understanding-models-views-and-controllers/ 

Regards,
Marta

**Comment by chrisblack910** [comment]
Hi Marta,

I downloaded the code from https://github.com/DigitalCurationCentre/DMPonline_v4 about 2 weeks ago. I am relatively new in Ruby actually only started using it with this project. I am in the process of checking these two files and plans their controllers and will let you know how this goes.

Thank you so much for the help thus far! :)

**Comment by chrisblack910** [comment]
Hi Marta,

I downloaded the project again yesterday and ran it but still, no luck :( I think i have just about exhausted my options. I am in South Africa and we need to have our own instance of the tool otherwise we would just simply use the current online one.

Regards,
Chris.

**Comment by sjDCC** [comment]
Hi Chris

Do you know there is an instance of DMPonline up and running in South Africa already? It's being run at UCT by Wesley Barry. They plan for it to be open to others, not restricted to UCT, so that may solve your problems. Which institution are you at?

We have some contacts at CPUT and through NeDICC and CSIR who may be able to help too. If you drop me an email on dmponline@dcc.ac.uk, I can put you in touch with relevant people.

The DCC is just starting to deliver services on behalf of other countries or unis outside of the UK where they don't have the capacity to do it themselves too. If the other options don't work out, we can look at doing that for you

All best

Sarah
