### ISSUE TITLE
attribute wayfless_entity supposed to be an integer?

### ISSUE THREAD

**Issue by nicolasfranck** [DigitalCurationCentre/DMPonline_v4#182]
The attribuut "wayfless_entity" in the model Organisation defined as an integer

cf. db/migrate/20130612113321_create_organisations.rb
cf. db/migrate/20130621101824_fix_column_names.rb

Is there a reason for this?

The code in app/controllers/users/omniauth_shibboleth_request_controller.rb cannot work:

```
idp = params[:idp] || current_user.organisation.wayfless_entity
```

Shouldn't this be a "string" or "text" (for long urls) to allow us to set IDP per organisation?

**Comment by DigitalCurationCentre** [comment]
Hi Nicolas,

This variable has not yet been used or tested. Initially was setup as a integer probably because we thought it would be an id saved. In the next git commit I'll add a migration to change it from an integer to a string.

Kind regards,
Marta
